# Read atlas mesh generated by AG

require(geomorph)
require(Morpho)
require(rgl2gltf)

dir <- "~/Documents/bhlab_misc/Atlas"

atlas_mesh <- read.ply(paste0(dir, "/MusCleanGPA_fromAG.ply"), ShowSpecimen = F)
atlas_lms <- as.matrix(read.csv(paste0(dir,"/mgpMeshLMsCleanGPA.csv")))

# symmetrize atlas_lms
sym <- readRDS("/home/kristen/Documents/bhlab_misc/landmark_sym.Rds")
atlas_lms <- Morpho::symmetrize(atlas_lms, as.matrix(sym$sym.pairings))

rm(sym)

