# Read atlas mesh generated by MG

require(geomorph)
require(Morpho)

dir <- "/home/kristen/Documents/bhlab_misc/Atlas"
atlas_mesh <- read.ply(paste0(dir, "/Atlas_mesh.ply"))

temp_lms <- suppressWarnings(read.table(paste0(dir, '/Atlas_landmarks.tag'), skip=5))
temp_lms <- as.matrix(na.omit(temp_lms[,1:3]))

atlas_lms <- matrix(as.numeric(temp_lms), nrow(temp_lms), ncol(temp_lms))
rm(temp_lms, dir)

# Remove some landmarks
rem <- c(337:430,  94, 325) # These are dupes or extra landmarks.
atlas_lms <- atlas_lms[-rem,]
rownames(atlas_lms) <- 1:748

# symmetrize atlas_lms
sym <- readRDS("/home/kristen/Documents/bhlab_misc/landmark_sym.Rds")
atlas_lms <- Morpho::symmetrize(atlas_lms, as.matrix(sym$sym.pairings))

rm(sym, rem)

